openapi: 3.0.0
info:
  title: Grievance System API
  version: 1.0.0
  description: REST API for AI-based Grievance Lodging and Tracking System
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: /api/v1
    description: API v1

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
                - full_name
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                full_name:
                  type: string
                phone:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input or user already exists

  /auth/login:
    post:
      summary: Login user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials

  /grievances:
    get:
      summary: List grievances
      tags:
        - Grievances
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: List of grievances
        '401':
          description: Authentication required

    post:
      summary: Create new grievance
      tags:
        - Grievances
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - description
              properties:
                title:
                  type: string
                description:
                  type: string
                location:
                  type: string
                priority:
                  type: string
                  enum: [low, medium, high]
                  default: medium
      responses:
        '201':
          description: Grievance created successfully
        '400':
          description: Invalid input
        '401':
          description: Authentication required

  /grievances/{id}:
    get:
      summary: Get grievance details
      tags:
        - Grievances
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Grievance details
        '401':
          description: Authentication required
        '403':
          description: Permission denied
        '404':
          description: Grievance not found

  /grievances/{id}/status:
    patch:
      summary: Update grievance status
      tags:
        - Grievances
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status_id
              properties:
                status_id:
                  type: integer
      responses:
        '200':
          description: Status updated successfully
        '400':
          description: Invalid status_id
        '401':
          description: Authentication required
        '403':
          description: Permission denied (officer/admin only)
        '404':
          description: Grievance not found

  /departments:
    get:
      summary: List all departments
      tags:
        - Reference Data
      responses:
        '200':
          description: List of departments

  /statuses:
    get:
      summary: List all statuses
      tags:
        - Reference Data
      responses:
        '200':
          description: List of statuses

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        full_name:
          type: string
        role:
          type: string
          enum: [citizen, officer, admin]

    Grievance:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          type: string
        department:
          type: string
        priority:
          type: string
        location:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Department:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string

    Status:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        order:
          type: integer
